name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          - 27.2
          - 28.1
          - snapshot
    steps:
      - uses: actions/checkout@v2

      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

      - name: Print emacs version
        run: |
          emacs --version

      - run: echo "$HOME/.eask/bin" >> $GITHUB_PATH
      - run: eask install --dev
      - run: make compile
      - run: make lint
      - run: make test
